feat: 코드 기능 일부 구현 및 정리
prgrms-web-devcourse/team-7sung-heycake-fe pull request #24
Opened 2023-02-22 10:02 UTC by zerosial

## 📌 이슈번호 

- close #21

## 👩‍💻 요구 사항 
### 해더
- [x]  로그인 , 회원정보에 Link 추가 (각 /login , /mypage로 임시 링크)
- [x]  색상 검정색과 기존 색 보고 좀 더 좋은것으로 변경

###  마켓 상세 페이지
- [x]  Stores 에서 Market으로 루트 변경

###  메인페이지
- [x]  코드가 난잡하게 흩어져 있어서 조금 더 깔끔하게 정리예정

2023-02-22 10:06 UTC, tooooo1 requested changes
고생하셨씁니다~ 굿굿굿

2023-02-22 10:06 UTC, tooooo1 commented on pages/market/[id].tsx
> +  );
```suggestion
  return <MarketProfile />;
```

이건 어떠신가요?

2023-02-22 16:25 UTC, zerosial commented on pages/market/[id].tsx
> +  );
좋아요!! 감사합니다 원래 해더 있던 자리였는데 ㅋㅋㅋ 😋

2023-02-22 16:38 UTC, zerosial commented
https://nextjs.org/docs/messages/no-document-viewport-meta

제가 옴긴부분에서 에러가 발생해서 meta 태그 다시 document -> app으로 옴겼습니다!! ☺

2023-02-23 05:49 UTC, Heojiyeon approved these changes
수고하셨습니다 :)

2023-02-23 06:13 UTC, tooooo1 approved these changes

2023-02-23 06:14 UTC, merged