feat: 상세페이지 마크업
prgrms-web-devcourse/team-7sung-heycake-fe pull request #25
Opened 2023-02-22 11:33 UTC by tooooo1

## 📌 이슈번호 

- close #1 

## 👩‍💻 요구 사항 

- 상세페이지
- 데이터 컴포넌트
- 이미지 추가

## 🎨 구현 스크린샷 

![image](https://user-images.githubusercontent.com/77133565/220608187-7484e3f4-c71b-4e06-9e3f-80eb7f78d1b4.png)

## ✅ PR 포인트

2023-02-22 16:38 UTC, zerosial requested changes
페이지 작성 수고하셧어요!! 👍

2023-02-22 16:38 UTC, zerosial commented on pages/orders/[id].tsx
> +  background-color: #e53e3e;
기존 정해뒀던 브랜드 컬러 이외에 
e53e3e
feebcb
c7c7c7

추가되었는데 혹시 색의 바리에이션을 조금 더 늘려도 될까요??
저도 색 추가할까 하다가 그냥 기존색으로 최대한 맞췄거든요 😂

2023-02-22 16:38 UTC, zerosial commented on pages/orders/components/DataTable.tsx
> +import styled from '@emotion/styled';
pages 안에 컴포넌트를 분리하는 것보다 현재 제가 components를 분리해뒀는데

그쪽 폴더에다 모으는게 어떨까 조심스럽게 의견 끄내봐요!!

(pages 안에는 route 될 파일들만.. 모으기?)

혹시 pages폴더 안에 분리한 이유가 있다면 듣고싶어요! 😊

2023-02-23 05:52 UTC, Heojiyeon approved these changes
수고하셨습니다 충일님~

2023-02-23 05:52 UTC, Heojiyeon commented on pages/orders/components/DataTable.tsx
> +import styled from '@emotion/styled';
저도 승훈님과 동일한 의견입니다!

2023-02-23 06:41 UTC, tooooo1 commented on pages/orders/[id].tsx
> +  background-color: #e53e3e;
말씀해주신대로 더 추가해야할거같아요 ㅎㅎ!
추가적으로 사용되는 컬러는 어느것이 있을지 리스트업 한 후에 시간 정해서 정하죠!

2023-02-23 06:41 UTC, tooooo1 commented on pages/orders/components/DataTable.tsx
> +import styled from '@emotion/styled';
감사합니다 리액트랑 다르네요! 수정 후에 다시 올릴게요!

2023-02-23 10:37 UTC, zerosial approved these changes
수고하셧습니다!!!

2023-02-23 10:37 UTC, merged