feat: 관리자 페이지 마크업 및 기능생성
prgrms-web-devcourse/team-7sung-heycake-fe pull request #44
Opened 2023-02-26 04:15 UTC by zerosial

## 📌 이슈번호 

- close #43 

## 👩‍💻 요구 사항 

## 관리자 페이지를 통해 업체 페이지의 승인 혹은 거절을 가능하게 한다

- [x] 운영자 로그인 페이지를 마크업한다
- [x] 운영자 승인 리스트 페이지를 마크업한다
- [x] 운영자는 /admin/login 을 통해 로그인 페이지에 접속할 수 있다
- [x]  운영자는 /admin에서 업체를 관리한다

## 🎨 구현 스크린샷 

![chrome_CYzMzBgfU8](https://user-images.githubusercontent.com/97251710/221391959-1d8a8198-0474-41f7-9b2a-70af2afd04b2.gif)
![SrpTKsvuMc](https://user-images.githubusercontent.com/97251710/221391962-1351b9c7-f8e6-482e-b573-5a1e52926755.gif)

## ✅ PR 포인트 

승인 혹은 거절한 리스트를 일괄로 보여주는 탭도 있으면 좋겠지만 시간상 제작하지 않았습니다.

간단하게 토글로 승인 혹은 거절을 할 수 있습니다.

2023-02-26 13:46 UTC, Heojiyeon reviewed
수고하셨습니다 승훈님~!

폼 라이브러리를 통해 추후에 리팩토링 진행하면 더 깔끔해질 것 같아요ㅎㅎ

2023-02-26 13:46 UTC, Heojiyeon commented on components/Admin/login.tsx
> +      </form>
제가 사용한 react-hook-form을 이용하시면 코드가 더 간단해질 것 같아요!

2023-02-27 04:21 UTC, tooooo1 requested changes
ㅋㅋㅋ 뚝딱이시네요 승훈님! 든든합니다 진짜!!

2023-02-27 04:21 UTC, tooooo1 commented on components/Admin/login.tsx
> +              <FormErrorMessage>Id 가 필요합니다</FormErrorMessage>
![image](https://user-images.githubusercontent.com/77133565/221472858-3bbe6f12-dacf-4131-b015-3e41ad5ce4a3.png)

입장하자마자 ID 입력하라는 경고메세지가 보여서 경험이 좋지 않았어요 ㅠㅠ 고려해주시면 더 좋을 것 같아요!

2023-02-27 04:21 UTC, tooooo1 commented on components/Admin/login.tsx
> +              <FormHelperText>운영자 Id를 입력해주세요</FormHelperText>
![image](https://user-images.githubusercontent.com/77133565/221472973-7eef15e7-2978-4c6b-a814-12d69c4b1e64.png)

입력을 했는데 id를 입력하라는 text는 부자연스럽다고 생각해요. 다른 방법이 있을까요?

2023-02-27 04:21 UTC, tooooo1 commented on components/Admin/login.tsx
> +              <FormHelperText>운영자 비밀번호를 입력해주세요</FormHelperText>
![image](https://user-images.githubusercontent.com/77133565/221473062-341dd702-ec36-44ca-8abc-e6601c930ec0.png)

비밀번호도 마찬가지로 UX적으로 고려해주시면 더 좋은 서비스가 될 것 같아요!

2023-02-27 04:21 UTC, tooooo1 commented on components/Admin/login.tsx
> +      console.log(inputPassword); */
```suggestion
```

주석처리보다 삭제하는건 어떨까요? 불필요한 것 같은데 git 로그에 다 남아서요! ㅎㅎ

2023-02-27 04:21 UTC, tooooo1 commented on components/Admin/marketItem.tsx
> +  /* console.log(marketSwitch); */
```suggestion
```

2023-02-27 05:20 UTC, zerosial commented on components/Admin/login.tsx
> +              <FormErrorMessage>Id 가 필요합니다</FormErrorMessage>
메세지를 아예 빼는거도 괜찮을거 같내요

어차피 관리자라 크게 의미가 없을지도..

2023-02-27 05:21 UTC, zerosial commented on components/Admin/login.tsx
> +              <FormHelperText>운영자 Id를 입력해주세요</FormHelperText>
경고랑 핼퍼 부분을 빼는게 좋아보이는데 빼는것도 괜찮을 거 같아요! 😁

수정해서 커밋하겠습니다

2023-02-27 05:21 UTC, zerosial commented on components/Admin/login.tsx
> +      console.log(inputPassword); */
이후 작업할때 편리하게 하려고 남겨뒀습니다 ^^

API 연결이후 삭제될 부분이라 큰 문제는 없어보여요

밑에도 같은 답변입니다! 👍👍

2023-02-27 05:23 UTC, zerosial commented on components/Admin/login.tsx
> +      </form>
이후 관리자 페이지 제작할때 지연님 작업 참고할게요 감사합니다!!

Sprint 5 전에 작업이 끝나면 5에서 작업할 예정입니다 😏

2023-02-27 09:55 UTC, tooooo1 approved these changes

2023-02-27 09:56 UTC, merged